### PR TITLE
[JENKINS-198] Revive nightly builds

### PR DESCRIPTION
**Pull request by rentzzz**
pipeline trigger job for paintroid/dev, catroid/dev and stand-alone regarding to issue [[JENKINS-198]](https://jira.catrob.at/browse/JENKINS-198).

### CODE REVIEW

**Comment by redeamer** [comment]
Please squash your commits and rebase them to current master

**Comment by mfuchs** [comment]
I don't like the concept of having a nighthly-job that triggers other jobs.
Each job themselves could have a nightly trigger instead.

I added  a more detailed comment to the story.

**Comment by rentzzz** [comment]
I got some review from Michael which still needs to be done.

**Comment by mfuchs** [comment]
I added a comment now to the story.

**Pull request closed without merging**
