### PR TITLE
new version of yaml file

### PR DESCRIPTION
**Pull request by thmq**
has to be changed for new language resource update (CAT-1307)

### CODE REVIEW

**Comment by avihric** [comment]
reminder @thmq we need to check this at next meeting :confounded:

**Comment by thmq** [comment]
I'm already shivering with terror :anguished:

**Comment by amix73** [comment]
Still relevant for Jenkins?

**Comment by avihric** [comment]
Honestly I don't know. Maybe @thmq can tell you more on this. I suppose since this is quite old, that it's not relevant anymore.

**Comment by mfuchs** [comment]
@thmq is this PR still relevant?

**Comment by avihric** [comment]
I talked to @thmq. This is not relevant anymore. Please close the PR.

**Comment by mfuchs** [comment]
Thanks for the info! :)

**Pull request closed without merging**
